
log:
  image: debian:stable
  variables:
    SSH_KEY: /root/.ssh/id_ed25519
    GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i $SSH_KEY"
  script:
    - apt-get update
    - apt-get -qy install --no-install-recommends git python3-requests ssh
    - ./log.py
    - git diff
    - git config user.name "$CI_PIPELINE_ID/$CI_JOB_ID"
    - git config user.email $CI_PROJECT_PATH@f-droid.org
    - git checkout -b autocommit
    - git add *.sha256 *.json
    - git commit *.sha256 *.json -m "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID" || exit 0
    - mkdir -pvm 0700 $(dirname $SSH_KEY)
    - echo $DEPLOY_KEY | base64 --decode > $SSH_KEY
    - chmod 0400 $SSH_KEY
    - git remote set-url --push origin "git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git"
    - git push origin autocommit:$CI_COMMIT_REF_NAME
